### ISSUE TITLE
Classroom - add a timer to display time limit before a test will expire

### ISSUE THREAD

**Issue by maxsv0** [maxsv0/mega-iq-ui#139]

**Comment by Aisangon** [comment]
@maxsv0 i found this library https://www.npmjs.com/package/ngx-countdown, what do you think?
Or should I rework the timer we had on classroom just to be displayed without depending on external library?

**Comment by maxsv0** [comment]
@Aisangon  This lib looks good we can definitely use it

**Comment by Aisangon** [comment]
Update: after trying several way to fix the timer issue when building, seems nothing is working at this moment. I will record this issue and maybe we can resolve later:

To reproduce:
Go to Classroom and following error message will apear in console 

`ERROR NullInjectorError: StaticInjectorError(X)[Uf -> t]: 
  StaticInjectorError(Platform: core)[Uf -> t]: 
    NullInjectorError: No provider for t!
    at ot.get (http://localhost:4000/main-es2015.5adaa2ef59a4f760f3d2.js:1:104827)
    at http://localhost:4000/main-es2015.5adaa2ef59a4f760f3d2.js:1:168845
    at t (http://localhost:4000/main-es2015.5adaa2ef59a4f760f3d2.js:1:169225)
    at qs.get (http://localhost:4000/main-es2015.5adaa2ef59a4f760f3d2.js:1:169376)
    at http://localhost:4000/main-es2015.5adaa2ef59a4f760f3d2.js:1:168845
    at t (http://localhost:4000/main-es2015.5adaa2ef59a4f760f3d2.js:1:169225)
    at qs.get (http://localhost:4000/main-es2015.5adaa2ef59a4f760f3d2.js:1:169376)
    at xm (http://localhost:4000/main-es2015.5adaa2ef59a4f760f3d2.js:1:222339)
    at Wm.get (http://localhost:4000/main-es2015.5adaa2ef59a4f760f3d2.js:1:230989)
    at gp (http://localhost:4000/main-es2015.5adaa2ef59a4f760f3d2.js:1:234834)`.

Browser: Chrome
NPM Version: 6.10.3

Issue caused by ngx-countdown
https://www.npmjs.com/package/ngx-countdown.

**Comment by Aisangon** [comment]
@maxsv0 Uninstalling npx-countdown no longer blocks users from accessing tests. I will push a new commit with the old countdown logic.
